# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        users:
            entity: { class: AppBundle\Entity\User, property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            guard:
                authenticators:
                    - AppBundle\Security\LoginFormAuthenticator
            logout:
                path: 'security_logout'
                target: 'security_login'

            logout_on_user_change: true
        api_secured:
            pattern: ^/api/
            stateless: true
            http_basic: ~

    access_control:
        - { path: ^/page1, roles: [ROLE_PAGE_1, ROLE_ADMIN] }
        - { path: ^/page2, roles: [ROLE_PAGE_2, ROLE_ADMIN] }
        - { path: ^/page3, roles: [ROLE_PAGE_3, ROLE_ADMIN] }
        - { path: ^/api/user, roles: [ROLE_PAGE_1, ROLE_PAGE_2, ROLE_PAGE_3, ROLE_ADMIN], methods: GET }
        - { path: ^/api/user, roles: [ROLE_ADMIN], methods: [POST, PUT, DELETE] }